### ISSUE TITLE
Where should themes be stored by default?

### ISSUE THREAD

**Issue by ff6347** [sebastian-meier/frontal-themes#1]
I would suggest having a folder in the the user home directory

```
~/.frontal/themes
```

with

```
git clone git@github.com:sebastian-meier/frontal-theme-example.git ~/.frontal/themes/example
```

everyone could store themes there. A bit like [grunt-init](https://github.com/gruntjs/grunt-init)

This would also allow storing config files there.

```
~/.frontal/config.json
```

**Comment by sebastian-meier** [comment]
Yepp this was also my first thought, maybe we could do it like processing, initially create a frontal-folder and if the user does not like to spam the user-directory she can choose another destination and move stuff...

For configs i though about using the standard user-app-path (library/application support/FRONTAL)... i think it depends if we want users to edit the config file by hand. so far i only have 
- theme folder
- current theme
- last presentation

as variables in the config, which can all three be modified through the interface...

**Comment by ff6347** [comment]
As discussed today I'm a fan of a manged folder by frontal called

```
~/.frontal   
```

It could contain
themes, settings.json, other things. So a backup of .dotfiles would manage this folder as well.
The application support is also a possibility but makes three paths

*nix --> home
win --> Documents
osx --> Library/Application Supprt

when using a 

~/.frontal we can do *nix and osx the same way

**Comment by sebastian-meier** [comment]
Agreed. 

A. As a temporary solution we keep a folder at location X (defined by user)

B. Target is a ~/.frontal folder managed through FRONTAL
Which means we need:
- Add Theme to folder
- Remove Theme from folder
- Update Theme manually or via repo
- Clone Theme from repo
- Detecting possible duplicates (replace / rename)

**Comment by ff6347** [comment]
Right. As discussed management will be a later feature.
